### ISSUE TITLE
Craft 2.5 compatible

### ISSUE THREAD

**Issue by joshangell** [engram-design/ImageResizer#3]
Is this compatible with Craft 2.5? I just chucked it in a project and the cropping modal is a bit borked, equally it couldn’t save the crop when I did get one done.

**Comment by engram-design** [comment]
So impatient :wink: I'm just working through our plugins at the moment, but this was on my list to do today! Craft 2.5 swapped out the cropping tool to use Jcrop instead. This is fixed in the [latest release](https://github.com/engram-design/ImageResizer/releases/tag/0.1.0) which also now requires Craft 2.5

**Comment by joshangell** [comment]
I know I'm ever so sorry 😢 but still, thanks!

-Josh

**Comment by engram-design** [comment]
@joshangell Nah all good - keep me on my toes! :smile:

**Comment by joshangell** [comment]
_And_ I gave you an extra easy issue to tick off ... :wink:

**Comment by engram-design** [comment]
You know me well :smile:
