### ISSUE TITLE
Non-destructive option not working

### ISSUE THREAD

**Issue by jamiewade** [engram-design/ImageResizer#47]
`Image Resizer will save a copy of your original image, untouched. This will be in a folder called originals, relative to the source image.`

### Description
I have enabled the 'Non-destructive' lightswitch in the plugin settings, but the above statement is not happening. Images are uploaded, re-named and re-sized correctly, but no `originals` folder is created. I can't see any trace of the original image.

### Additional info

- Plugin version: 2.0.3
- Craft version: 3.0.26.1

**Comment by jamiewade** [comment]
## Update

After looking into this a little further, it seems there is actually two major issues with the plugin:

### 1. `originals` folder creation ignoring 'Restrict uploads to a single folder?'
The asset field I was testing uploads into a dynamic folder. The `originals` folder _was_ being created, but in the **root** of my asset source, not in the folder the images were actually being uploaded into.
I only spotted the `originals` folder when navigating the AmazonS3 bucket, because....

### 2. Asset re-index does not trigger after upload
When the `originals` folder doesn't exist, the plugin will create it for you. However it won't show in Craft unless you run an Asset re-index. This is the case for me using AmazonS3.

**Comment by engram-design** [comment]
So the tricky part to your first point is that when Image Resizer fires, its in the context of the asset, not the asset field, or the owner entry. That owner entry and field context is required to be able to resolve the dynamic path you're setting in your field. Because we can't get that information, the next-best thing is to create this folder in the root of the volume. There's not a great deal we can do about that without a PR to Craft itself to send us that information on the event.

I'll see what can be done about re-indexing, although not at the cost of potential performance (I'm not sure if asset re-indexing can be done per-folder, or all-or-nothing).

**Comment by engram-design** [comment]
Second part fixed in [2.0.4](https://github.com/verbb/image-resizer/releases/tag/2.0.4).

We'll have to see what our options are with the Craft crew on the first part.

**Comment by jamiewade** [comment]
@engram-design Thanks for looking into this Josh, I look forward to seeing if P&T are able to help us any further.
